import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

/**
 * Lyrics PDF generation via pdfkit. Bundled Noto fonts (fetched by
 * `scripts/fetch-fonts.mjs`) are registered when present so Indic scripts
 * render; if a font is missing we fall back to the built-in Helvetica so the
 * endpoint never crashes (Latin/Roman still render fine).
 */

const FONT_DIR = path.resolve(__dirname, '../../assets/fonts');

const FONT_FILES: Record<string, { file: string; name: string }> = {
  telugu: { file: 'NotoSansTelugu-Regular.ttf', name: 'NotoTelugu' },
  devanagari: { file: 'NotoSansDevanagari-Regular.ttf', name: 'NotoDevanagari' },
  tamil: { file: 'NotoSansTamil-Regular.ttf', name: 'NotoTamil' },
  kannada: { file: 'NotoSansKannada-Regular.ttf', name: 'NotoKannada' },
  malayalam: { file: 'NotoSansMalayalam-Regular.ttf', name: 'NotoMalayalam' },
  latin: { file: 'NotoSans-Regular.ttf', name: 'NotoLatin' },
};

function scriptKeyFor(languageCode: string): keyof typeof FONT_FILES {
  const c = (languageCode || '').toLowerCase();
  if (c.startsWith('te')) return 'telugu';
  if (/^(hi|sa|mr|ne|kok)/.test(c)) return 'devanagari';
  if (c.startsWith('ta')) return 'tamil';
  if (c.startsWith('kn')) return 'kannada';
  if (c.startsWith('ml')) return 'malayalam';
  return 'latin';
}

/** Register every available bundled font once; return a (code -> fontName) resolver. */
function makeFontResolver(doc: PDFKit.PDFDocument): (languageCode: string) => string {
  const registered: Partial<Record<string, string>> = {};
  for (const [key, entry] of Object.entries(FONT_FILES)) {
    const fp = path.join(FONT_DIR, entry.file);
    if (fs.existsSync(fp)) {
      try {
        doc.registerFont(entry.name, fp);
        registered[key] = entry.name;
      } catch {
        /* ignore unusable font file */
      }
    }
  }
  return (languageCode: string) =>
    registered[scriptKeyFor(languageCode)] || registered.latin || 'Helvetica';
}

export interface LyricsPdfSection {
  language: string;
  languageCode: string;
  content: string;
}

export interface LyricsPdfInput {
  title: string;
  meta: { label: string; value?: string | null }[];
  sections: LyricsPdfSection[];
  siteName?: string;
}

/** Stream a generated lyrics PDF into the given writable (usually an HTTP response). */
export function streamLyricsPdf(out: NodeJS.WritableStream, input: LyricsPdfInput): void {
  const doc = new PDFDocument({ margin: 50, size: 'A4', info: { Title: input.title } });
  doc.pipe(out);

  const fontFor = makeFontResolver(doc);
  const latin = fontFor('en');

  doc.font(latin).fontSize(22).fillColor('#7c2d12').text(input.title, { align: 'center' });
  doc.moveDown(0.3);

  const metaLine = input.meta
    .filter((m) => m.value)
    .map((m) => `${m.label}: ${m.value}`)
    .join('    •    ');
  if (metaLine) {
    doc.font(latin).fontSize(10).fillColor('#6b7280').text(metaLine, { align: 'center' });
  }

  doc.moveDown(0.6);
  doc.strokeColor('#e5d5c0').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.8);

  for (const section of input.sections) {
    if (doc.y > 720) doc.addPage();
    doc.font(latin).fontSize(13).fillColor('#b45309').text(section.language.toUpperCase());
    doc.moveDown(0.25);
    doc
      .font(fontFor(section.languageCode))
      .fontSize(13)
      .fillColor('#111827')
      .text(section.content || '', { align: 'left', lineGap: 5 });
    doc.moveDown(0.9);
  }

  doc
    .font(latin)
    .fontSize(8)
    .fillColor('#9ca3af')
    .text(`Generated by ${input.siteName || 'Swara'}`, 50, 800, { align: 'center', width: 495 });

  doc.end();
}
